name: CI
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
      - name: Diff Checker tests
        run: |
          chmod +x ./tests/diff_checker_tests.sh
          ./tests/diff_checker_tests.sh
        shell: bash
